### ISSUE TITLE
Error in lme4::.simulateFun(object = sm, nsim = nsim, seed = seed) : could not find function "sfun"

### ISSUE THREAD

**Issue by erwinia** [lme4/lme4#284] opened 2015-03-04 17:50 UTC
Hi! I use glmer.nb for count data =

Model1<-glmer.nb(Count ~  Traitement +(1 | Bloc)+offset(log(n.Total)) ,data= Data))
Model0<-glmer.nb(Count ~  1 +(1 | Bloc)+offset(log(n.Total)) ,data= Data))

All is good, except when I try to simulate new data, for instance with PBmodcomp from pbkrtest.

PBmodcomp(Model1, Model0, nsim = 1000) # could not find function "sfun"

Am I doing something wrong or is there internal machinery missing in glmer.nb ? It works if I use family=poisson.

Thank you for your help!

**Comment by bbolker** [comment] 2015-03-09 21:16
Reproducible example:

```
library("lme4")
set.seed(101)
dd <- data.frame(f=factor(rep(1:10,each=50)),
                 x=runif(500),
                 y=rnbinom(500,size=2,mu=2))
## gg <- transform(grouseticks,cYEAR=YEAR-mean(YEAR))
## g1 <- glmer.nb(TICKS~(1|LOCATION),data=gg,verbose=1000)
g1 <- glmer.nb(y~x+(1|f),data=dd)
g0 <- glmer.nb(y~1+(1|f),data=dd)
library(pbkrtest)
PBmodcomp(g1,g0,nsim=10)
```

**Comment by bbolker** [comment] 2015-03-09 21:22
it looks like things need to be hacked a bit in order to allow simulation from a `glmer.nb` fit ... not impossible, just hacky

**Comment by lponisio** [comment] 2015-05-14 23:54
I am having the same trouble as erwinia, and actually cannot get the code Ben posted above to work either. Simulate() with a negative binomial model also returns the same error. I have the latest versions of R and lme4. Any suggestions? (for a reproducible example of code that returns the 'could not find function "sfun"' error, at least for me, see Ben's code above).

Thanks!

**Comment by aosmith16** [comment] 2015-05-21 18:39
@lponisio I believe the code above is to *reproduce* the problem, not solve it. 

A few weeks ago, I looked a little closer at what kind of hacks would be needed to get `simulate` working for `glmer.nb` fits.  I found that, in particular, one main reason this won't work right now is that there is currently no method for negative binomial models in `simfunList`.  Another difficulty I ran into is that an object from a `glmer.nb` stores it's family name as "Negative Binomial (Theta)".  With `glmer` fits, the name is just, e.g., "binomial".  

The general simulation process appears to be that `.simulateFun` pulls out the name of the family name and then calls the function for that family from `simfunList` to actually do the simulation.  

Here's what I changed `simfunList$negative.binomial` to, although this was just my best guess based on the functions for the other families.  Notice that the only way I could figure out how to get the estimate of theta was to pull it out of the model family name. 
```
function (object, nsim, ftd = fitted(object)) {
	wts <- weights(object)
	if (any(wts != 1))
		warning("ignoring prior weights")
	rnegbin(nsim * length(ftd), ftd, theta = as.numeric(gsub("[[:alpha:][:blank:]+?&/\\()]", "", object@resp$family$family)) )
}
```
In `simulateFun`, I added a conditional statement to set the family name to "negative.binomial" so it would match the name in `simfunList`.  After line 86 (the line that reads `family <- object@resp$family`) of `simulateFun`  I added 
```
if(gsub("[^[:alpha:]]", "", family$family) == "NegativeBinomial") {
				family$family <- "negative.binomial"
			}
``` 
 It's been a month or so since I tried this, but I believe those are all the changes I made.  I could use `simulate` and `bootMer` with `glmer.nb` after those changes, but I haven't tried `PBmodcomp`.

**Comment by bbolker** [comment] 2015-05-21 18:41
thanks @aosmith16 ! this looks really useful, I will check it out ...

**Comment by lponisio** [comment] 2015-05-22 23:00
worked perfectly for me! Thanks @aosmith16.

**Comment by bbolker** [comment] 2015-05-28 03:41
closed by 2f49f19d7 (although still need to add to NEWS)

**Comment by florianhartig** [comment] 2019-09-24 12:56
Hi, seems this issue also appears for inverse Gaussian, reproducible example see https://github.com/florianhartig/DHARMa/issues/125 - I would recommend to reopen.

**Comment by bbolker** [comment] 2019-09-24 13:21
The inverse Gaussian is a new issue.  It would be good to try to fix this: also to include a meaningful error message for families without simulation methods.

**Closed** 2019-09-25 01:56 UTC
