### ISSUE TITLE
simulate.merMod is unhappy with newdata when it shouldn't be

### ISSUE THREAD

**Issue by tmalsburg** [lme4/lme4#197] opened 2014-04-10 16:47 UTC
I fit a model using data from a pilot study:

    tt <- lmer(ltt ~ 1 + Region.length + (1|subj) + (cond|item), d)

Then I used that model for a simulation:

    > ss <- simulate(tt, nsim=1, seed=101, newdata=d)

I know that it's redundant to specify `d` in this case.  The purpose of specifying the `d` is to illustrate the problem that I encountered:

    > ss <- simulate(tt, nsim=1, seed=101, newdata=rbind(d))

    Error in mkNewReTrms(object, newdata, compReForm, na.action = na.action,  : 
      random effects specified in re.form that were not present in original model

1. `d` and `rbind(d)` should be equivalent and hence there shouldn't be any problem with using `rbind(d)` instead of `d`.
2. I didn't specify `re.form` and the default is NA.  So what does this error message mean?

**Comment by AnnePdM** [comment] 2015-04-28 13:32
Re: the comments about problems with simulate and newdata made on 14th April 2014, I have had similar problems with my analysis; newdata being a shorter length than the original dataset.  Is there any work around yet?

**Comment by bbolker** [comment] 2015-04-28 14:22
I *think* that this is resolved by https://github.com/lme4/lme4/commit/8dc8cf017491b484c383e765627b5d235574798d ; @AnnePdM , are you willing to try the development version?  Unless anyone can come up with a reproducible example, I'm going to close this ...

**Comment by tmalsburg** [comment] 2015-04-28 17:27
@bbolker I just tried the development version and it works as expected.  (But `fm1` in line 3 and 4 of your code above needs to be replaced by `tt`.)

Thank you!

**Comment by tmalsburg** [comment] 2015-05-22 14:51
Using the latest development version of R and lme4:

```R
    library(lme4)
    d <- sleepstudy
    d$Subject <- factor(rep(1:18, each=10))
    fm1 <- lmer(Reaction ~ Days + (Days | Subject), d)
    # Add 18 new subjects for power analysis:
    d <- rbind(sleepstudy, sleepstudy)
    d$Subject <- factor(rep(1:36, each=10))
    d[d$Subject %in% 19:36,]$Reaction <- NA
    simulate(fm1, newdata=d, allow.new.levels=T, nsim=1)
```

This gives me an error:

    Error in `row.names<-.data.frame`(`*tmp*`, value = c("1", "2", "3", "4",  : 
    invalid 'row.names' length

However, when I skip the second to last line (where the NAs are assigned), I don’t get an error.  For the purpose of the simulation it shouldn’t matter what the content of the Reaction column is, right?

**Comment by tmalsburg** [comment] 2015-05-22 15:05
The earlier workaround to extract the parameters from the merMod and to call `simulate.formula` does not work here:

```R
    d <- sleepstudy
    d$Subject <- factor(rep(1:18, each=10))
    fm1 <- lmer(Reaction ~ Days + (Days | Subject), d)
    fm1.parameters <- list(
        beta = fixef(fm1),
        theta = getME(fm1, "theta"),
        sigma = getME(fm1, "sigma"))
    # Add 18 new subjects for power analysis:
    d <- rbind(sleepstudy, sleepstudy)
    d$Subject <- factor(rep(1:36, each=10))
    d[d$Subject %in% 19:36,]$Reaction <- NA
    simulate(~ Days + (Days|Subject), newdata=d, newparams=fm1.parameters,
            family=gaussian, allow.new.levels=T)
```
produces
```R
Error in `row.names<-.data.frame`(`*tmp*`, value = c("1", "2", "3", "4",  : 
  invalid 'row.names' length
```

**Comment by mmaechler** [comment] 2015-05-22 15:45
I'm looking at this... ... but at a few other things simultaneously.  Give me 24 hours.

**Comment by tmalsburg** [comment] 2015-05-22 16:29
No rush, I'm ok with the workaround for now.  But it is easy to trigger this bug and users will get bitten.  A clean solution would therefore be great.  Thanks!

**Comment by bbolker** [comment] 2015-05-22 19:04
OK, thanks.  Might we be able to use `model.frame()` to get just the relevant columns?  Martin, do feel free to consult with me -- a lot of my recent commits have been in this area ...

**Closed** 2015-05-23 23:36 UTC

**Comment by tmalsburg** [comment] 2015-05-24 04:02
Thank you, @mmaechler!

**Comment by VerbingNouns** [comment] 2018-08-08 13:09
RE: https://github.com/lme4/lme4/issues/197#issuecomment-40117256 
```
Error in sim.reff + if (cond.sim) matrix(rnorm(n * nsim), ncol = nsim) else 0 : 
  non-conformable arrays
```
I am getting this error now, based on code adapted from @tmalsburg's [gist](https://gist.github.com/tmalsburg/df66e6c2ab494fad83ee):
`d$simulated <- simulate(fm1, seed=1, newdata=d[-28], re.form=NA, allow.new.levels=T)$sim_1`

Column 28 is the input for the y-axis, but I've tried a number of configurations and am stuck, and googling brought me to this old issue thread. Does the solution not work anymore, or am I missing something? Thanks!

**Comment by bbolker** [comment] 2018-08-08 13:15
Hmm.  All of the example code I've tried from the thread above seems to work (including the code in the gist - but I could always have missed something), so a reproducible example would be helpful so we can debug/troubleshoot ...

**Comment by bbolker** [comment] 2018-08-08 13:55
To clarify: the error occurs when the model *converges* but not when it *fails to converge*? (That's a little surprising, because there's not generally a *structural* difference between models that do and don't give convergence warnings ...)

A few possibilities:
- you could simulate data with similar structure to yours; you could try fitting the model for many (100?) simulated data sets and see if you can get a mixture of converging and non-converging outcomes. Something like:

```
dd <- expand.grid(age=7:10,speaker=factor(1:100))
dd$logDigit <- rnorm(400)
dd$ethnicity2 <- ...
dd$logProp <- simulate(~[formula], newdata=dd,
    newparams = list(beta=c([one value per fixed-effect parameter],
                                 theta=c(1,0,1), ## equal variances for intercept and age, no correlation
                                 sigma = 1))
```
etc.

Or maybe you could take your actual predictor variables and simulate only the response variable, if that would provide sufficient protection
- if the data are non-public but not sensitive (e.g. not protected by patient confidentiality or a non-disclosure agreement), you could send them privately to me to help me diagnose - not as useful as something we can post publicly, but better than nothing

**Comment by VerbingNouns** [comment] 2018-08-08 14:07
> the error occurs when the model converges but not when it fails to converge?
Yes… there very well could be another confound I haven't identified. The data are more sparse than I'd like, but there's nothing to be done about that.

I have to move on for a bit, but I'll either post something reproducible or send you something privately in the next day or two. Thanks!

**Comment by mmaechler** [comment] 2018-08-08 15:03
Thank you Lauren @VerbingNouns .   @bbolker : Maybe we should provide a function in lme4 which anonymizes a data frame + model formula
(need both: replace all variable names by y, x1, x2,....), also replacing data frame rownames by 1:n,
also replacing factor levels of variable x<n> by e.g., A<n>, B<n>, C<n>, ... (well actually something smarter), and optionally jitters the continuous variables.

If a user would get all this (new data frame, new formula) very quickly, I'd hope users would be willing to share such anonymized data... and we'd rep.rex.'s in such cases.

**Comment by VerbingNouns** [comment] 2018-08-10 14:37
Hi, here's the [anonymised/simplified dataset](https://github.com/VerbingNouns/gendocrine/blob/master/datasets/20180810-anon_data.csv) and code that I've been using:

```
library(tidyverse);library(lme4)

d0 <- read.csv("20180810-anon_data.csv",header=TRUE)
fm1 <- lmer(logProp ~ logDigit+age+ethnicity+logDigit:ethnicity+
  interviewer+vowel+consonant+foll_interval+ 
  (1+age|speaker), preasp2,REML=TRUE)
summary(fm1)

d0 %>%
  mutate(speaker = as.numeric(speaker)+22) -> d

d <- rbind(d0, d)
d$logProp <- ifelse(d$speaker %in% 23:44, NA, d$logProp)

d$predicted <- predict (fm1, newdata=d, allow.new.levels=T)
d$simulated <- simulate(fm1, seed=1, newdata=d, re.form=NA, allow.new.levels=T)$sim_1
```
…which results in the following error:
`Error in sim.reff + if (cond.sim) matrix(rnorm(n * nsim), ncol = nsim) else 0 : non-conformable arrays`

I think the convergence/nonconvergence thing was just because of the content of whichever column I included/excluded to change the result and not directly tied to the model outcome.
