### ISSUE TITLE
Predict method is very slow

### ISSUE THREAD

**Issue by humana** [lme4/lme4#636] opened 2021-07-23 14:01 UTC
I'm trying to figure out why the predict call would take extremely long (about 10 to 15 seconds) on when newdata contains a single row?

The LMER model I fit on data containing 68,000 rows and 12 columns.  One of columns is a factor variable with 8598 levels, and another has 2549 levels, which are nested.  Whether I call predict on the entire training data set, or just 1 single out-of-sample datapoint, it takes the same amount of time (i.e. the performance doesn't seem to depend on the amount of stuff I'm inputing to newdata in the predict function).

I was thinking maybe when using a formula to describe the model and one of the factors has a lot of levels would lead to some heavy computation in some of the predict code, but I'm not really sure where I should be looking debug this?

Here is the use case:  This fitted model is going to be used for online prediction with new data via a Plumber API.  Thus I need it to be as performant as possible, definitely under 1 second, preferably a few hundred milliseconds.

**Comment by bbolker** [comment] 2021-07-23 14:12
This is an interesting case. I think it may be related to the issue described in #635 .

**Comment by humana** [comment] 2021-07-23 15:29
Yes the model has a number of interactions:

`sv ~ vt*pc + fg + pv +  st*dp + sh + ks + (1 + ks|mm_ry/mmv_ry)`

mm_ry is the factor with 2549 levels and mmv_ry is the factor with 8598 levels

I'm going to try your suggestion and see if it improves things, thanks.

Just out of curiosity, why do we need to re-evaluate the formula when calling predict at all?  Isn't the design matrix already created during model fitting? I see the returned object of lmer also contains the entire dataset used to fit the model (called frame).  I would even like to remove that completely before saving the model to disk, and would expect the predict function to carry on working.

**Comment by humana** [comment] 2021-07-23 15:57
> This is an interesting case. I think it may be related to the issue described in #635 . Does your model have interactions? Can we see a little more detail about the model?
> 
> If my suspicion about #635 is correct, then a workaround is to replace the nested RE term (e.g) `(1|a/b)` with `(1|a) + (1|int_ab)`, where `int_ab` is a factor variable you create upstream via `factor(paste(a,b, sep="_"))`
> 
> If you want to explore this yourself you can `debug(lme4:::predict.merMod)`, step through, and see where things get slow.

After replacing the nested RE term as you suggested it's blazingly fast. So this is definitely the issue.

**Comment by bbolker** [comment] 2021-07-23 19:59
Closing as duplicate of #635

**Closed by bbolker** 2021-07-23 19:59 UTC

**Comment by bbolker** [comment] 2021-07-25 23:26
Can you try `remotes::install_github("lme4/lme4@interaction_eval")` and see if it resolves this issue (without the workaround)?

**Comment by humana** [comment] 2021-07-26 08:46
I get the same performance when using the interaction_eval branch as I do when manually replacing the nested RE terms.  So I think that commit fixes the issue.
