### ISSUE TITLE
Function  'cholmod_factor_ldetA' not provided by package 'Matrix' 

### ISSUE THREAD

**Issue by AngelGeorgeJohn** [lme4/lme4#807] opened 2024-07-11 12:07 UTC
For fitting a GLMER model using lme4, I am getting the below error,

Error in initializePtr() : 
  function 'cholmod_factor_ldetA' not provided by package 'Matrix'

Would you be able to fix this issue?

Many thanks in adavnce

**Comment by bbolker** [comment] 2024-07-11 13:16
Please see [here](https://stackoverflow.com/questions/77481539/error-in-initializeptr-function-cholmod-factor-ldeta-not-provided-by-pack), particularly [this answer](https://stackoverflow.com/a/77532685/190277) ...

**Comment by bbolker** [comment] 2024-07-12 00:25
Please let us know if this works, or provide further information if it doesn't (e.g. results of `sessionInfo()` in a clean session after loading `lme4`), otherwise we'll close this issue ...

**Comment by naj-r** [comment] 2024-07-18 12:42
Hello, I am experiencing the same. I reinstalled the Matrix and lme4 packages. I see "package ‘lme4’ is not available for this version of R". I now also get the error that I need the Rcpp package, which I tried installing and even downloaded manually from CRAN [ install.packages("C:/path_to_file/Rcpp_1.0.13.tar.gz", repos = NULL, type = "source") ] but it is not working. I am also wanting to run a linear mixed effect model. 
I am using the latest R version (4.4.1)

**Comment by bbolker** [comment] 2024-07-18 19:54
Hi @naj-r,

This is very challenging to troubleshoot, especially remotely.

You say that

```
install.packages("C:/path_to_file/Rcpp_1.0.13.tar.gz", repos = NULL, type = "source") 
```
is not working. Please let us know (either in a new post or by editing your current comment) exactly what error message you're getting ("it is not working" is too vague to be useful), in a text format [not as an image/screenshot].

You **should** be able to install everything without needing `Rcpp`/compiler/etc. via

[restart R, make sure that no .RData files/packages are automatically loaded]. Then:

```r
oo <- options(repos = "https://cran.r-project.org/")
utils::install.packages("Matrix")
utils::install.packages("lme4")
options(oo)
```

Again, if this doesn't work please post the *exact* output/error messages.

**Comment by CornfusedNeedHelp** [comment] 2024-07-20 16:12
Hi Ben,

I am inexperienced R user. I did this: 

oo <- options(repos = "https://cran.r-project.org/")
utils::install.packages("Matrix")
utils::install.packages("lme4")
utils::install.packages("lmerTest")
utils::install.packages("rockchalk")
options(oo)

library(Matrix)
library(lme4)
library(lmerTest)
library(rockchalk)

imm23 <- read.table('imm23.dat')

fit_gmcx_Kreft <- lmer(math ~ 1 +homework_dev+homework_mn +(1 +homework_dev|schid), data=gmc(imm23,c("homework"),"schid"))
summary(fit_gmcx_Kreft)


Here is the error I received:

> fit_gmcx_Kreft <- lmer(math ~ 1 +homework_dev+homework_mn +(1 +homework_dev|schid), data=gmc(imm23,c("homework"),"schid"))
Error in initializePtr() : 
  function 'cholmod_factor_ldetA' not provided by package 'Matrix'
> summary(fit_gmcx_Kreft)
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'object' in selecting a method for function 'summary': object 'fit_gmcx_Kreft' not found
>

**Comment by bbolker** [comment] 2024-07-20 16:18
OK, next iteration: please start a clean R session (again) and run *only* this code:

```r
oo <- options(repos = "https://cran.r-project.org/")
utils::install.packages("Matrix")
utils::install.packages("lme4")
options(oo)
library(lme4)
m <- lmer(Reaction ~ 1 + (1|Subject), sleepstudy)
summary(m)
sessionInfo()
```
(I have omitted `lmerTest` and `rockchalk` to try to keep the example as minimal as possible.)

Please cut and paste *all* of the output from this session into your next post.

**Comment by CornfusedNeedHelp** [comment] 2024-07-20 16:30
Thank you. Here are the results:


R version 4.3.2 (2023-10-31 ucrt) -- "Eye Holes"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Previously saved workspace restored]

> oo <- options(repos = "https://cran.r-project.org/")
> utils::install.packages("Matrix")
Installing package into ‘C:/Users/mistrys/AppData/Local/R/win-library/4.3’
(as ‘lib’ is unspecified)
Warning message:
package ‘Matrix’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
> utils::install.packages("lme4")
Installing package into ‘C:/Users/mistrys/AppData/Local/R/win-library/4.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.r-project.org/bin/windows/contrib/4.3/lme4_1.1-35.5.zip'
Content type 'application/zip' length 4554282 bytes (4.3 MB)
downloaded 4.3 MB

package ‘lme4’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\mistrys\AppData\Local\Temp\RtmpCOJpwx\downloaded_packages
> library(lme4)
Loading required package: Matrix
Warning messages:
1: package ‘lme4’ was built under R version 4.3.3 
2: In check_dep_version() : ABI version mismatch: 
lme4 was built with Matrix ABI version 1
Current Matrix ABI version is 0
Please re-install lme4 from source or restore original ‘Matrix’ package
> m <- lmer(Reaction ~ 1 + (1|Subject), sleepstudy)
Error in initializePtr() : 
  function 'cholmod_factor_ldetA' not provided by package 'Matrix'
> summary(m)
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'object' in selecting a method for function 'summary': object 'm' not found
> sessionInfo()
R version 4.3.2 (2023-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default


locale:
[1] LC_COLLATE=English_United States.utf8 
[2] LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lme4_1.1-35.5  Matrix_1.6-1.1

loaded via a namespace (and not attached):
 [1] lattice_0.22-6 splines_4.3.2  pbivnorm_0.6.0 stats4_4.3.2   nloptr_2.1.1  
 [6] grid_4.3.2     lavaan_0.6-18  mnormt_2.1.1   compiler_4.3.2 boot_1.3-30   
[11] tools_4.3.2    nlme_3.1-165   minqa_1.2.7    Rcpp_1.0.12    quadprog_1.5-8
[16] MASS_7.3-60   
>

**Comment by bbolker** [comment] 2024-07-20 16:43
OK, thanks.

By looking [here](https://cran.r-project.org/bin/windows/contrib/4.3/PACKAGES) we can see that it doesn't list a binary (pre-compiled) version of `Matrix` for Windows for R version 4.3. That puzzles me, since the package is indeed available [here](https://cran.r-project.org/bin/windows/contrib/4.3/lme4_1.1-35.5.zip). Please try:

```r
utils::install.packages("https://cran.r-project.org/bin/windows/contrib/4.3/lme4_1.1-35.5.zip",
   repos = NULL)
```
(again from a clean session. Note that the "[Previously saved workspace restored]" message means that you are *not* really starting a completely clean session, although I don't think it's going to be a problem here).

Two alternative solutions:

* update your R to the latest version, 4.4. In the long run this might be easiest; there will be lots of little annoyances like this one caused by being slightly out of date. (However, this will mean that you'll have to re-install other packages.)
* install the `Matrix` package from source. To do this you'll need to follow the instructions [here](https://cran.r-project.org/bin/windows/Rtools/rtools43/rtools.html) to install development tools and then `utils::install.packages("Matrix", type = "source")`.

**Comment by CornfusedNeedHelp** [comment] 2024-07-20 16:58
Thank you, Ben. Very helpful. Updating R to the latest version, 4.4 did the trick.

**Comment by bbolker** [comment] 2024-07-20 16:59
OK.

**Comment by naj-r** [comment] 2024-07-21 16:04
> Hi @naj-r,
> 
> This is very challenging to troubleshoot, especially remotely.
> 
> You say that
> 
> ```
> install.packages("C:/path_to_file/Rcpp_1.0.13.tar.gz", repos = NULL, type = "source") 
> ```
> 
> is not working. Please let us know (either in a new post or by editing your current comment) exactly what error message you're getting ("it is not working" is too vague to be useful), in a text format [not as an image/screenshot].
> 
> You **should** be able to install everything without needing `Rcpp`/compiler/etc. via
> 
> [restart R, make sure that no .RData files/packages are automatically loaded]. Then:
> 
> ```r
> oo <- options(repos = "https://cran.r-project.org/")
> utils::install.packages("Matrix")
> utils::install.packages("lme4")
> options(oo)
> ```
> 
> Again, if this doesn't work please post the _exact_ output/error messages.


Hi Ben, 

Thanks for the response. Sure, I can post the errors (sorry that it is in German - I changed the system language to english but it still appears in German:
```
oo <- options(repos = "https://cran.r-project.org/")
utils::install.packages("Matrix")

Warnung: kann nicht auf den Index für das Repository https://cran.r-project.org/src/contrib zugreifen:
  kann URL 'https://cran.r-project.org/src/contrib/PACKAGES' nicht öffnen
Warnung: kann nicht auf den Index für das Repository https://cran.r-project.org/bin/windows/contrib/4.4 zugreifen:
  kann URL 'https://cran.r-project.org/bin/windows/contrib/4.4/PACKAGES' nicht öffnen
Warnmeldung:
Paket ‘Matrix’ ist nicht verfügbar for this version of R

Eine Version dieses Paketes für ihre R Version ist evtl woanders verfügbar,
siehe unter
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
```

Then I tried the next line, with the following error:
```
utils::install.packages("lme4")

Warnung: kann nicht auf den Index für das Repository https://cran.r-project.org/src/contrib zugreifen:
  kann URL 'https://cran.r-project.org/src/contrib/PACKAGES' nicht öffnen
Warnung: kann nicht auf den Index für das Repository https://cran.r-project.org/bin/windows/contrib/4.4 zugreifen:
  kann URL 'https://cran.r-project.org/bin/windows/contrib/4.4/PACKAGES' nicht öffnen
Warnmeldung:
Paket ‘lme4’ ist nicht verfügbar for this version of R

Eine Version dieses Paketes für ihre R Version ist evtl woanders verfügbar,
siehe unter
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
```

**Comment by bbolker** [comment] 2024-07-21 16:09
All of these "kann nicht auf den Index für das Repository https://cran.r-project.org/bin/windows/contrib/4.4" suggest that you're having a network problem, possibly firewall related? Can you download the zip files from CRAN and install them from the local zip file?

>

**Comment by bbolker** [comment] 2024-07-22 13:12
In other words, first try

```r
utils::install.packages("https://cran.r-project.org/bin/windows/contrib/4.4/Matrix_1.7-0.zip", repos = NULL)
utils::install.packages("https://cran.r-project.org/bin/windows/contrib/4.4/lme4_1.1-35.5.zip", repos = NULL)
```
which should work around not being able to find the `PACKAGES` file online (for whatever reason). If that again fails, then download the files from those URLs and install them via `utils::install.packages(file.choose(), repos = NULL)`, using the file browser to navigate to wherever you downloaded them.

**Comment by bbolker** [comment] 2024-07-29 15:47
Any luck with this? If I don't hear back from you I'll close the issue (it would be nice to know if the problem is resolved one way or the other.)

**Comment by naj-r** [comment] 2024-08-01 11:45
Hi Ben,

Thanks for your advice. I tried your method but I kept running into issues with lme4 package and its dependency on Rcpp. Then I contacted the IT team of my institute and they recommended I uninstall and reinstall R from the Software Center and use the packages there (to get the packages with their SSL certificates). I tried this and now the packages have all loaded correctly. However, after attempting to run my mixed effects model, I get the same error as I had in the beginning: 

`my_model_ebf <- lmer(infant_hb ~ anemia * time_point * bf + (1|participantID), data=data1)

"Error in initializePtr() : 
  function 'cholmod_factor_ldetA' not provided by package 'Matrix' "
`

It seems I am running in circles with this and am unsure what to do.

**Comment by bbolker** [comment] 2024-08-01 13:47
I don't think I can help unless you try to follow my advice exactly, and post the exact output you get. What version of R you have and where you installed it from really shouldn't matter (as long as it is a version >= 4.4.0).

Please:

* start a clean R session
* try this:

```r
utils::install.packages("https://cran.r-project.org/bin/windows/contrib/4.4/Matrix_1.7-0.zip", repos = NULL)
utils::install.packages("https://cran.r-project.org/bin/windows/contrib/4.4/lme4_1.1-35.5.zip", repos = NULL)
```

Post *all* of the error messages you get from doing that.

If you get network errors, then download the packages directly (go to those URLs) and install them locally using

```r
utils::install.packages(file.choose(), repos = NULL)
```

where you use the file browser to find and select the zip files you downloaded.

**Comment by bbolker** [comment] 2024-08-02 13:11
Yes, if that's possible it would definitely be easiest to start by updating your version of R to at least 4.4.0.  (Not impossible if you need to stick with an older version, but much harder.)

**Comment by rasouli-nahid** [comment] 2024-09-02 12:59
Hi, Having the same issue for a couple of days! I updated my R-studio and it's the latest version.
I followed your instruction: 
 > utils::install.packages("https://cran.r-project.org/bin/windows/contrib/4.4/Matrix_1.7-0.zip", repos = NULL)
Installing package into ‘C:/Users/rasouli/AppData/Local/R/win-library/4.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.r-project.org/bin/windows/contrib/4.4/Matrix_1.7-0.zip'
Content type 'application/zip' length 4967000 bytes (4.7 MB)
downloaded 4.7 MB

package ‘Matrix’ successfully unpacked and MD5 sums checked
> utils::install.packages("https://cran.r-project.org/bin/windows/contrib/4.4/lme4_1.1-35.5.zip", repos = NULL)
Installing package into ‘C:/Users/rasouli/AppData/Local/R/win-library/4.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.r-project.org/bin/windows/contrib/4.4/lme4_1.1-35.5.zip'
Content type 'application/zip' length 4557157 bytes (4.3 MB)
downloaded 4.3 MB

package ‘lme4’ successfully unpacked and MD5 sums checked

**Comment by bbolker** [comment] 2024-09-02 18:44
The thing that looks fishy here is that you're installing from the '4.4' directory of the repository into `win-library/4.3`. This strongly suggests that you have *not* updated R to the latest version (which is 4.4.1). (Note that RStudio and R need to be updated separately.) 

You say "the same issue". By that do you mean an error about "cholmod_factor_ldetA", or do you instead get the error that the next-most-recent poster received, i.e. "This is R 4.3.[something], package ‘Matrix’ needs >= 4.4.0" ?

If so, by far the path of least resistance will be to update your R version (not your RStudio version) [and make sure that the updated version is being loaded by RStudio]. `R.version.string` ought to tell you something about version 4.4.1.

- If you think you've already updated R, please post the results of `sessionInfo()` from a *clean* R session (with only the `lme4` package loaded).
- In any case, please post the exact error/warning messages you're getting (this thread is now long and tangled enough that it's good to be explicit).

**Comment by bbolker** [comment] 2024-09-08 17:39
@rasouli-nahid , any further useful information?  Did you resolve the problem?

**Comment by rasouli-nahid** [comment] 2024-09-08 19:25
Well the problem was previous version of R was still on the computer .since I wasn’t admin Account to delete it I couldn‘t do so much. But once both R and R-studio uninstalled and reinstalled  by IT center., There was no error

**Comment by bbolker** [comment] 2024-10-02 20:57
I'm going to go ahead and close this (hopefully others with the same issue will still be able to find it ...)

**Closed by bbolker** 2024-10-02 20:57 UTC
