### ISSUE TITLE
Warning about rank deficient

### ISSUE THREAD

**Issue by Atsui1012** [lme4/lme4#628] opened 2021-05-17 04:04 UTC
Hi

Thank you very much for your help.

When we ran Package lme4 to our longitudinal data, we got following warnings repeatedly.

> fixed-effect model matrix is rank deficient so dropping 2 columns / coefficients
> boundary (singular) fit: see ?isSingular 

Nevertheless, we got some results. Are these valid?
When I look for the Q&A in some Statistic Forums, sometimes I found the previous answer that we do not have to care these warnings.

In actuality, how do we deal with these warnings?

Thank you for your time.

**Comment by mmaechler** [comment] 2021-05-17 06:49
duplicate of #534 .  Please ask on R-sig-mixed-models (the mailing list), giving much more information *there*

**Closed by mmaechler** 2021-05-17 06:49 UTC

**Comment by bbolker** [comment] 2021-05-17 16:08
and for the record, this was already [answered on the mailing list](https://stat.ethz.ch/pipermail/r-sig-mixed-models/2021q2/029481.html)
