### ISSUE TITLE
Error : object ‘sigma’ is not exported by 'namespace:lme4'

### ISSUE THREAD

**Issue by MYaseen208** [lme4/lme4#374] opened 2016-04-17 02:07 UTC
After updating `lme4 (1.1-12)`, I'm getting this error when I invoke `varComp` package.

    library(varComp)
    Error : object ‘sigma’ is not exported by 'namespace:lme4'
    Error: package or namespace load failed for ‘varComp’

**Comment by bbolker** [comment] 2016-04-17 02:28
This is an interaction between R version , lme4 version (*not* new to this version of lme4), and presumably `varComp` version.  What version of `varComp`?  When I look at the `NAMESPACE` file in the [tarball of the latest CRAN version](https://cran.r-project.org/src/contrib/varComp_0.1-360.tar.gz) (version 0.1-360), I don't see `sigma` at all.  More generally, are you up to date on all packages?

**Comment by MYaseen208** [comment] 2016-04-17 03:25
Solved!!!

Rebooting the machine and using `update.packages(ask = FALSE, repos = 'http://cran.rstudio.org')` again solved the issue. Thanks

**Comment by MYaseen208** [comment] 2016-04-17 05:22
In new session of `R` has the same problem again.

**Comment by bbolker** [comment] 2016-04-17 12:19
This is going to be very hard to debug without a reproducible example.  What happens if you use `R --vanilla` to start a **clean** session?  What versions of R, `varComp`, etc. are you using?

```
R Under development (unstable) (2016-04-14 r70486)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.4 LTS

...

other attached packages:
[1] varComp_0.1-360

loaded via a namespace (and not attached):
 [1] minqa_1.2.4        MASS_7.3-45        Matrix_1.2-4       RLRsim_3.1-2      
 [5] mgcv_1.8-12        Rcpp_0.12.4        mvtnorm_1.0-5      splines_3.4.0     
 [9] nlme_3.1-126       grid_3.4.0         nloptr_1.0.4       lme4_1.1-12       
[13] CompQuadForm_1.4.1 lattice_0.20-33    quadprog_1.5-5    
```

**Comment by mmaechler** [comment] 2016-04-18 06:31
@MYaseen208 : Do something like
```
pkgs <- c("nloptr", "nlme", "minqa", "RLRsim") # <---  all the non-base packages/ namespaces loaded above
pd <- sapply(pkgs,  packageDescription)
sapply(pd, `[[`, "Built")
```
and see if the R versions are at least 3.2.0... 
and you need to re-install packages whose installation is too old.

**Comment by bbolker** [comment] 2016-04-18 23:40
`lme4` *should* work even with older versions of R (if all packages are consistent with that version ...)  The `NAMESPACE` file contains conditional code that will export `sigma` iff the R version is >=3.3.0.

```
if(getRversion() >= "3.3.0") {
    importFrom("stats", sigma)
} else {
    export(sigma)
}
```

What's most puzzling is that `varComp` (at least in the current Github version) doesn't even contain any significant references to `sigma`: neither in the [NAMESPACE file](https://github.com/gitlongor/varComp/blob/master/NAMESPACE) nor [anywhere in the GH repository](https://github.com/gitlongor/varComp/search?utf8=%E2%9C%93&q=sigma).  The problem *may* lie somewhere in one of the imported packages ...

```
quadprog, Matrix, MASS, CompQuadForm, RLRsim, SPA3G, mvtnorm, nlme, stats, utils, graphics
```

But this level of recursion is a bit too much for me to tackle.

- have you considered [submitting a varComp issue](https://github.com/gitlongor/varComp/issues), which might at least get one step closer to the ultimate source of the problem?
- are you using MRAN (the Microsoft/Revolution R "snapshot" repo), which might be getting you older versions of some packages?
- might you have different versions of (e.g.) `nlme` installed in a system and a user library? See [this SO answer](http://stackoverflow.com/questions/35469385/package-car-unable-to-load-wrong-version-of-nlme/35786859#35786859) ...

**Comment by bbolker** [comment] 2016-04-19 17:14
in the absence of more information and/or a reproducible example I'm going to be tempted to close this issue ...

**Comment by bbolker** [comment] 2016-04-30 18:29
no more information/not reproducible, closing ...

**Closed by bbolker** 2016-04-30 18:29 UTC

**Comment by mnazarov** [comment] 2016-09-12 10:43
I just wanted to notice that the conditional statement in the NAMESPACE means 'sigma' is not exported for R versions >3.3.0, and so all the packages that import sigma from lme4 would need the same conditional statement, if they want to support both R>3.3 and <3.3... I just encountered this issue with my package that had `importFrom(lme4, sigma)` when someone tried to install it on R 3.3.1.
I wonder if there are any drawbacks in having
    
    if(getRversion() >= "3.3.0") {
        importFrom("stats", sigma)
    }
    export(sigma)
instead?

**Comment by bbolker** [comment] 2016-09-12 13:35
I don't know. @mmaechler ?

**Comment by mmaechler** [comment] 2016-09-12 16:45
I did put the export()  into the else clause on purpose because I'd like others to get sigma from stats rather than lme4... after all that had been the reason I had ported it to R (stats).

Also, lme4 depends on R >= 3.30 itself I'd really not want to export it,  and @mnazarov proposal would just do that.
I think importing and re-exporting is something one should only do as "last resort"  because it exactly does lead to masking, as soon as people have both 'stats' and 'lme4' attached.

**Comment by mnazarov** [comment] 2016-09-12 16:54
@mmaechler, thanks for your reply, it makes sense. I agree this makes things cleaner, and my issue is very minor.

**Comment by hhhsunnn** [comment] 2024-10-11 02:13
Hello,

I just encountered with the same issue when downloading the lme4ord package via remotes::install_github("stevencarlislewalker/lme4ord"). I have rebooted my machine and also updated all my packages, but the issue existed. The exact error information and my session information were attached below, and I am currently using Rstudio 2024.04.2 with R 4.4.1 on macOS Sonoma 14.6.1. Could you please figure it out? Thanks for working on it.

==========
remotes::install_github("stevencarlislewalker/lme4ord")
Downloading GitHub repo stevencarlislewalker/lme4ord@HEAD
── R CMD build ──────────────────────────────────────────────────────────────────
✔  checking for file ‘/private/var/folders/mg/9j2hr8gd24571y6pkdqbhq2mjx64_3/T/Rtmp6M0fPa/remotes7d633525dc8/stevencarlislewalker-lme4ord-5f62664/DESCRIPTION’ ...
─  preparing ‘lme4ord’:
✔  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘lme4ord_0.0-3.tar.gz’
   Warning: invalid uid value replaced by that for user 'nobody'
   Warning: invalid gid value replaced by that for user 'nobody'
   
* installing *source* package ‘lme4ord’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error: object ‘sigma’ is not exported by 'namespace:lme4'
Execution halted
ERROR: lazy loading failed for package ‘lme4ord’
* removing ‘/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/lme4ord’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/mg/9j2hr8gd24571y6pkdqbhq2mjx64_3/T//Rtmp6M0fPa/file7d6648b0fca/lme4ord_0.0-3.tar.gz’ had non-zero exit status

==========
R version 4.4.1 (2024-06-14)
Platform: aarch64-apple-darwin20
Running under: macOS Sonoma 14.6.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.16.2 magrittr_2.0.3    dplyr_1.1.4      

loaded via a namespace (and not attached):
 [1] desc_1.4.3        utf8_1.2.4        R6_2.5.1          tidyselect_1.2.1 
 [5] remotes_2.5.0     glue_1.8.0        tibble_3.2.1      pkgconfig_2.0.3  
 [9] generics_0.1.3    lifecycle_1.0.4   ps_1.8.0          cli_3.6.3        
[13] processx_3.8.4    fansi_1.0.6       callr_3.7.6       vctrs_0.6.5      
[17] compiler_4.4.1    rstudioapi_0.16.0 tools_4.4.1       pkgbuild_1.4.4   
[21] curl_5.2.3        pillar_1.9.0      rlang_1.1.4
