### ISSUE TITLE
Issue with simulate.merMod() functionality with gamm4 mer object

### ISSUE THREAD

**Issue by jbrightross** [lme4/lme4#575] opened 2020-06-04 08:49 UTC
I am trying to carry out a parametric bootstrapping procedure for estimating the CI of random effect repeatability (ICC) in a generalized additive mixed model (from the gamm4 package). The problem is, I can't figure out how to do so without using the simulate.merMod() function embedded in lme4, and this function seems not to work with the "mer" object produced by gamm4.

Attempting to pass the $mer object from a gamm4() fit to simulate.merMod() should in theory work, but instead I get "Error in FUN(X[[i]], ...) : random effects specified in re.form that were not present in original model". Digging into the code, I assume it's because the mer object has splines fit as random effects, and so the re.form() value that simulate.merMod() is trying to assign contains random effects (the splines) that weren't in the original fit. So I've tried specifying re.form = (1|random-effect-name), re.form = NA, re.form = "(1|random-effect-name)" (by the way, some guidance in the documentation about how to format the re.form argument would go a long way), but the closest I get to anything else is "Error in mkNewReTrms(object, rfd, re.form, na.action = na.action, allow.new.levels = allow.new.levels) : 
  object 'ReTrms' not found".

Can you provide any guidance on how to finagle the function to work for this object? I've re-written existing repeatability code (from the rptR package) to work in all other ways except for the simulate() procedure, and it's the only thing keeping me from completing an analysis.

**Comment by bbolker** [comment] 2020-06-04 22:24
I too have found `gamm4` objects hard to work with. I have a stash of "gamm4 utils" that implement prediction etc., but I don't seem to have tackled simulation. Could we start with a reproducible example (I know, it would be fairly easy to put one together myself)?

**Comment by bbolker** [comment] 2020-06-04 22:25
OK, not that hard.

```
library(gamm4)
library(lme4)

## from ?gamm4
set.seed(0) 
dat <- gamSim(1,n=400,scale=2) ## simulate 4 term additive truth
## Now add 20 level random effect `fac'...
dat$fac <- fac <- as.factor(sample(1:20,400,replace=TRUE))
dat$y <- dat$y + model.matrix(~fac-1)%*%rnorm(20)*.5
br <- gamm4(y~s(x0)+x1+s(x2),data=dat,random=~(1|fac))

lme4:::simulate.merMod(br$mer)
```

**Comment by bbolker** [comment] 2020-06-05 14:48
I just copied the first example from `?gamm4`.  You may be misunderstanding my comment: it *doesn't* work for me. I confirm that it's a problem (although arguably not a bug in `lme4`: with respect to the `gamm4` developers, there are a lot of loose ends like this that make `gamm4` a little hard to use)

**Comment by jbrightross** [comment] 2020-06-05 15:50
Ah, I see--sorry, I thought for some reason that code had worked for you. And agreed! gamm4 can be finnicky--though overall I'm a big fan. Do let me know if you figure out any workarounds for it--I simply don't have the technical experience to dig this far into the function, but I'd love to be able to bootstrap the GAMM model and am at my wit's end with it. Also let me know if there's anything I can do--provide you with the real data, etc. etc.

**Comment by bbolker** [comment] 2020-10-04 02:12
This should (?) be fixed now ... haven't checked the results carefully at all, though, if you can check and see if results actually make sense that would be great.

**Closed** 2020-10-05 16:22 UTC
