### ISSUE TITLE
Predicting nested models

### ISSUE THREAD

**Issue by alireza202** [lme4/lme4#339] opened 2015-11-03 01:44 UTC
My model looks like this:

>lmer(formula = y ~ x1 + x2 + x3 + 
(1 | cat/subcat) +
(x1 + x2 + x3 || cat), 
data = df) -> model1

and it runs, no problem. However, when I want to predict newData with it:

>predict(model1, newdata = newData)

it gives this error:

>Error: couldn't evaluate grouping factor subcat:cat within model frame: try adding grouping factor to data frame explicitly if possible

newData has both cat and subcat columns. I tried adding subcat:cat as a concatenation of subcat and cat, but it didn't work. Any idea how to solve this problem?

**Comment by bbolker** [comment] 2015-11-04 22:14
Is there any chance that you could provide a reproducible example ... ?  That will make it easier to get to this ...

**Comment by alireza202** [comment] 2015-11-05 02:56
As I was trying to make a data set as an example, I figured out that the problem was with levels of cat and subcat. When I concatenated the "df", and "newData", and separated them again, the problem was solved.

**Comment by bbolker** [comment] 2015-11-05 12:58
So ... can you create a data set that *does* generate the specified error?  (And as a bonus, a similar one that doesn't?)  Or do you feel the problem is resolved now?

**Comment by alireza202** [comment] 2015-11-05 18:25
I wish I had a better idea why it's solved. It's definitely about the levels in the factors, but I can't say exactly why. Unfortunately I don't have a complete grasp of how the levels and factors work in R.

**Comment by bbolker** [comment] 2015-12-20 16:49
Until we have reproducible answer here I'm going to close this ...

**Closed by bbolker** 2015-12-20 16:49 UTC
