### ISSUE TITLE
Lower and Upper parameters in nlmerControl -> optCtrl are being ignored/Unused

### ISSUE THREAD

**Issue by anku44v8** [lme4/lme4#432] opened 2017-08-06 14:37 UTC
The lower and upper parameters that need to be passed to the optimization function in order to get parameter estimates in the desired range are always ignored (get warning message Unused arguments). It's always set to -Inf to Inf, Need to be able to change this.

Code chunk: 
function (optimizer, fn, par, lower = -Inf, upper = Inf, control = list(), 
          adj = FALSE, calc.derivs = TRUE, use.last.params = FALSE, 
          verbose = 0L) 
{
  optfun <- getOptfun(optimizer)
  optName <- if (is.character(optimizer)) 
    optimizer
  else deparse(substitute(optimizer))[[1L]]
  **lower <- rep(lower, length.out = length(par))
  upper <- rep(upper, length.out = length(par))**
...
}

**Comment by bbolker** [comment] 2017-09-12 15:23
can you give a simple reproducible example to help work on this?

**Comment by bbolker** [comment] 2017-09-12 18:39
A crude implementation of this is done.

It requires the user to specify bounds (lower and/or upper) for *all* of the parameters, i.e. random-effect plus fixed-effect.  So far there is no testing for this requirement/informative error message, or documentation thereof, other than this comment right here  :-(

Please test and let me know if it works for you.

**Comment by anku44v8** [comment] 2017-09-14 12:16
So, I'm trying to fit a power model of this form - 
y= ∑ (β_i*(x_i )  ^ (α_i))  + ε
S.T. 0 < α_i < 1 - Fixed part and -inf < β_i < inf - random across a category
the above model has two parameters to be estimated for each variable with a bound on the α parameter.

Ex: Fitting a linear model instead of the above mentioned form in order to reduce complexity
library(lme4)
library(nlme)
library(nloptr)
library(optimx)
nform <- ~(beta_o + (beta_V * (nitro)))
nfun <- deriv(nform,
              namevec=c("beta_o",
                        "beta_V"),
              function.arg=c("nitro",
                             "beta_o",
                             "beta_V"))
start.vec <- c(beta_o = 1,
               beta_V = 1)
nonlinear.model.bound <- nlmer(yield ~ nfun(nitro,
                                            beta_o,
                                            beta_V) ~ (beta_V|Block),
                               data = Oats,
                               control = nlmerControl(optimizer = "optimx",
                                                      optCtrl = list(method = "nlminb",
                                                                     lower = c(0,0),
                                                                     upper = c(10,1))),
                               start = start.vec)

Gives the following Warning message:
Warning messages:
1: In nlminb(start = par, objective = ufn, gradient = ugr, lower = lower,  :
  unrecognized control elements named ‘lower’, ‘upper’ ignored
2: In optwrap(control$optimizer[[1]], devfun, rho$pp$theta, lower = rho$lower,  :
  convergence code 1 from optimx
3: In nlminb(start = par, objective = ufn, gradient = ugr, lower = lower,  :
  unrecognized control elements named ‘lower’, ‘upper’ ignored
4: In optwrap(control$optimizer[[2]], devfun, par = c(rho$pp$theta,  :
  convergence code 1 from optimx
But works perfectly if the bounds are removed!!

Please find attached a script for building model with nls and nlmer functions (parameters are bounded by a range)
[nlm_git.txt](https://github.com/lme4/lme4/files/1302865/nlm_git.txt)

Hope this helps!! :)

**Comment by bbolker** [comment] 2017-09-16 23:09
I think this is working (sort of).

```
  control = nlmerControl(optimizer = "optimx",
                    optCtrl = list(method = "nlminb",
                    maxit=10000,
                    iter.max=10000,  
                    eval.max=10000,
                                       lower = c(0,0,0),
                                   upper = c(Inf,10,1)))
```

- I'm getting false convergence/convergence warnings, not sure what's up with that
- have to set bounds for the random-effects parameters as well

Does the development version (`devtools::install_github("lme4/lme4")`) work for you now?

**Comment by bbolker** [comment] 2017-09-24 19:05
I'm going to close this since it's presumptively fixed; will reopen if requested.

**Closed by bbolker** 2017-09-24 19:05 UTC
