### ISSUE TITLE
Description of allow.new.levels does not match implemented behavior.

### ISSUE THREAD

**Issue by tmalsburg** [lme4/lme4#306] opened 2015-05-22 19:50 UTC
The documentation for the parameter `allow.new.levels` in `simulate.merMod` says:

> ... if TRUE, then the prediction will use the unconditional (population-level) values for data with previously unobserved levels (or NAs).

However, the simulation below shows that this is not true.  In the simulation, I added another 18 subjects to the sleepstudy data set and found that the new subjects have the same statistical properties as old subjects.  Perhaps, someone copied the description from the manpage of `predict.merMod` and forgot to adapt it? 

```R
library(lme4)

# Fit model using the original data:
d <- sleepstudy
d$Subject <- factor(rep(1:18, each=10))
fm1 <- lmer(Reaction ~ Days + (Days|Subject), d)

# Add 18 new subjects:
d <- rbind(sleepstudy, sleepstudy)
d$Subject <- factor(rep(1:36, each=10))

# Simulate old and new subjects 1000 times:
params <- lapply(1:1000, function(i) {
    message(i)
    d$simulated <- simulate(fm1, newdata=d[-1], allow.new.levels=T)$sim_1
    # A small number of models fail to converge:
    fm.old <- lmer(simulated ~ Days + (Days | Subject), subset(d, Subject%in%1:18))
    fm.new <- lmer(simulated ~ Days + (Days | Subject), subset(d, Subject%in%19:36))

    c(fixef(fm.old), getME(fm.old, "theta"), getME(fm.old, "sigma"),
	fixef(fm.new), getME(fm.new, "theta"), getME(fm.new, "sigma"))
})

params <- do.call(rbind, params)

par(mfrow=c(1,3), mar=c(2,3,1,1))
plot(density(params[,3]), main="Subject intercepts", ylim=c(0,2))
lines(density(params[,9]), col="red")

plot(density(params[,5]), main="Subject Days", ylim=c(0,9))
lines(density(params[,11]), col="red")

plot(density(params[,4]), main="Correlation", ylim=c(0,6))
lines(density(params[,10]), col="red")

legend("topright", lty=c(1,1), col=1:2, c("old subjects", "new subjects"), bg="white")
```

**Edit:** Does it actually make sense to distinguish between old and new factor levels for the purpose of simulation?  If not, perhaps it would make sense to remove that parameter.

**Comment by tmalsburg** [comment] 2015-05-26 17:53
More details and plots can be found here: https://gist.github.com/tmalsburg/df66e6c2ab494fad83ee

**Comment by bbolker** [comment] 2015-05-27 21:14
OK, having looked at this carefully I think I see the issue, and it may be one of semantics/expectation -- there are a few possibilities for resolving it, I think.  At the very least, we may have to work on the `simulate` documentation some more, since it took me a few minutes of head-scratching to figure out/remember how it was supposed to work!  Here's the basic protocol:
* using `predict`, compute a "deterministic" part of the simulated model based on the fixed effects **and on the conditional modes of any random effects that are included in re.form**; since the default value of `re.form` is `NA` (don't include any conditional modes in the predicted values).
* now simulate new values for any random effects that are **not** included in `re.form` and add them to the predicted values
* now simulate from the conditional distribution (Normal, Poisson, binomial ...)

Here's how this works -- and why it doesn't do what you expect -- in the default case with new levels in the RE grouping variables.

* in the first stage, no random effects are included in the prediction, so the values for *all* groups (whether included in the original model or not) are 0
* in the second stage, new random effect values are chosen for *all* groups ... so the new factor levels and the old factor levels behave the same.

If you use `re.form=NULL` (include all random effects) you might get results more as you expect -- the fitted conditional modes should be used for the original levels, and zero for the new levels (I haven't tested this).

This and previous discussions elsewhere raise a couple of questions:

* is the current interface flexible enough?  Right now it assumes that *either* a given RE term will be included in the prediction *or* that it will have a new value chosen.  I can imagine use cases where one wants to "zero out" certain REs, i.e. include them in neither the prediction nor the simulation.
* how do we explain the current behaviour more clearly in the documentation?
* as expressed previously in a CrossValidated question (I'll look it up later), it would be nice to allow the simulation to choose from the conditional *distribution* of the conditional modes (at the moment we have only the choices of using the exact conditional mode *or* sampling unconditionally).

**Comment by tmalsburg** [comment] 2015-05-28 02:45
I see.  Explaining this without walking people through the algorithm (as you did above) is going to be difficult. It doesn't help that `re.form` has a somewhat unfortunate definition. The meaning of the typical values, `NULL` and `NA`, is not intuitively clear.  Wouldn't it be better to have a parameter `use.conditional.modes` (`TRUE` or `FALSE`) instead of `re.form`?  The documentation of that parameter could point out that conditional modes are only used where available, i.e. not for new levels.  For compatibility with the current implementation, the default value of `use.conditional.modes` would be `FALSE`.  I see that `re.form` is more powerful but if someone wants to use a different random effect structure for simulation, they can always use `simulate.formula` which gives full flexibility to those how know what they are doing.

**Comment by tmalsburg** [comment] 2015-05-28 02:53
I'd like to add that the implemented default behaviour is actually what I would typically want.  I use `simualate.merMod` for power analyses (following your tutorial on RPubs) and in this context it doesn't make sense to simulate data for the specific individuals that were used for the collection of the pilot data.  The actual experiment will sample from the same subject population but exclude people who participated in the pilot.

**Comment by bbolker** [comment] 2015-05-28 02:58
These are all good points. (Historically, I don't think `simulate.formula` existed until later than most of the rest of the interface.) I'm really nervous about changing the interface (every time we change it we use up some good-will/make it even harder for us to think about changing it in the future) ... if/when we change it I'd like to think about incorporating possibilities for simulating from the conditional distributions (as discussed above) and any other likely possibilities we can think of (for prediction, it would be nice to be able to general *marginal* predictions, at least approximately). In the near future, I think all I'll do will be to add more details/try to clarify the documentation ...

**Comment by tmalsburg** [comment] 2015-05-28 03:16
An improved documentation certainly will go a long way in addressing this issue.  And yes, incompatible changes should be avoided if possible.

**Comment by tmalsburg** [comment] 2015-05-28 04:25
I just tried setting `re.form=NULL`

    d$simulated <- simulate(fm1, seed=1, newdata=d[-1], re.form=NULL,
                            allow.new.levels=T)

and that produced an error message:

    Error in levelfun(r, n, allow.new.levels = allow.new.levels) : 
      new levels detected in newdata

When I do the same with `re.form=NA`, I get the expected result.  Given your description above this seems to be a bug.

**Comment by bbolker** [comment] 2015-05-28 13:56
bug fixed.  Are you willing to take a look at https://github.com/lme4/lme4/commit/3d3fb97b27fa1f97aad9303430c467fce994fb31and see if it seems reasonably helpful?

**Comment by tmalsburg** [comment] 2015-05-28 16:39
> If a random effect is included in \code{re.form}, it will be \emph{conditioned on} - that is, the conditional modes of that random effect will be included in the deterministic part of the simulation.

At this point you might want to point out that new levels (cf. allow.new.levels) will have no random variation because we don't have conditional modes for them.  This highlights that `re.form=NULL` doesn't make much sense when there are new levels; at least I can't think of a use case right now.  It's unfortunate, that there is no way to use the conditional modes for the old levels but to sample new random effects values for the new levels. Or am I missing something?

**Comment by bbolker** [comment] 2015-05-28 17:58
I would actually argue that using the conditional modes for the observed levels while drawing the modes of the unobserved levels from the full (unconditional) distribution is actually inconsistent on statistical grounds (although I'm sure *someone* could make a defensible use case for it); the conditional modes for the unobserved levels *are* equal to the population mode.

The case that would split the difference/make the most  would be the one we can't currently do, i.e. simulate based on the conditional *distribution* -- the conditional distribution for the observed levels would be the Normal distribution with the conditional mean and variance, while the conditional distribution for the unobserved levels would be the full (unconditional) variance of the random effect ...

**Comment by bbolker** [comment] 2015-05-28 17:59
closed by 781071ad1e (I could be talked into re-opening it if necessary)

**Comment by tmalsburg** [comment] 2015-05-28 18:33
Hm, I still find it confusing. `re.form=NULL` is supposed to mean "include all random effects" but there seem to be no random effects for the new subjects when I set `re.form=NULL`: http://pages.ucsd.edu/~tvondermalsburg/R/subject_means_reform_null.png

`re.form=NA` is supposed to mean "include no random effects" but I get these results when I use that setting: http://pages.ucsd.edu/~tvondermalsburg/R/subject_means.png

So for the new subjects `re.form` seems to be doing the exact opposite from what the documentation says.

If I understand it correctly, `re.form` is not so much about the inclusion of random effects, it seem to be about the inclusion of the conditional modes.  Perhaps, there is some ambiguity in our use of the term "random effects"?  I read it to mean the estimated variance in subject intercepts and slopes (in the sleepstudy example).

**Comment by bbolker** [comment] 2015-05-29 02:24
We're running into a wall here. I think I understand your confusion, but I'm running out of different ways to explain.  I've been a little more careful to say that "using" a random effect means *conditioning on its fitted values* (so "not using it" means simulating a value for it), i.e. I've changed the definition of `re.form` to

> formula for random effects to condition on.  If \code{NULL}, condition on all random effects; if \code{NA} or \code{~0}, condition on no random effects.  See Details.

and the Details:

>    \item{The \code{re.form} argument allows the user to specify how the
      random effects are incorporated in the simulation.  All of the
      random effects terms included in \code{re.form} will be
      \emph{conditioned on} - that is, the conditional modes of those
      random effects will be included in the deterministic part of the
      simulation. (If new levels are used (and \code{allow.new.levels}
      is \code{TRUE}), the conditional modes for these levels will be
      set to the population mode, i.e. values of zero will be used for
      the random effects.)  Conversely, the random effect terms that are
      \emph{not} included in \code{re.form} will be \emph{simulated
      from} - that is, new values will be chosen for each group based on
      the estimated random-effects variances.

>  The default behaviour (using \code{re.form=NA}) is to condition on
      none of the random effects, simulating new values for all of the
      random effects.

Is that any better?

**Comment by tmalsburg** [comment] 2015-05-29 03:17
Yes, I think it's better.  The situation is still not completely satisfying but that's not the documentation's fault but due to how `re.form` is defined.  I understand that you don't want to break users' code but perhaps there is a way to reparameterize `simulate` such that `re.form` can still be used by legacy code.  But that's not in the scope of this issue which can be closed as far as I'm concerned.

**Closed** 2015-05-29 18:19 UTC

**Comment by bbolker** [comment] 2015-05-29 18:26
If you feel like it, I'd be happy to hear what your ideas are for a new interface (with appropriately flexible, but still clear, control of whether a given term was conditioned on/simulated from its conditional distribution/simulated from its unconditional distribution ...)

**Comment by isaactpetersen** [comment] 2020-04-25 14:26
Thank you very much for your development of this useful package.  I'm running into an issue where I receive the following error when trying to make predictions from a newdata object: `"Error in levelfun(r, n, allow.new.levels = allow.new.levels) : 
  new levels detected in newdata"`.  I'm not sure how to troubleshoot this because I also receive the same error when I set the newdata object as the *same data that was used to fit the model*.  I wasn't sure where to post this issue, but it seemed similar to some of what was described in the above thread.

Of course, I can set `allow.new.levels = TRUE`, but this seems dangerous because I don't believe I'm trying to make predictions based on any new levels of random effects or factor variables (although I am predicting "out-of-range" for the timepoints spanned by each rater).  I have a suspicion it has to do with the `rater` factor and its interactions with other variables (i.e., creating dummy-coded variables for fitting the model), but I'm not sure.

I'm attaching a script, model, and data file for a reproducible example.  Any help you could provide would be greatly appreciated.  Thanks in advance!
[Example.zip](https://github.com/lme4/lme4/files/4533143/Example.zip)
