### ISSUE TITLE
"condition has length > 1" warning with confint.merMod profile method

### ISSUE THREAD

**Issue by jacob-long** [lme4/lme4#440] opened 2017-10-03 16:27 UTC
I got a new warning today running package tests for my package that has a function that calls `profile.merMod`. I have upgraded R 3.4.2 since the last test, though I can't recall if I ever ran tests successfully with the current CRAN version (1.1-14). I'm using macOS Sierra, but I'd be surprised if that matters.

Here's the full warning message:

> Warning in if (parm == "theta_") { : 
>   the condition has length > 1 and only the first element will be used

The issue can be reproduced on my machine by running the relevant pieces of the example:

```
library(lme4)
fm1 <- lmer(Reaction ~ Days + (Days|Subject), sleepstudy)
fm1P <- confint(fm1, method="profile")
```

It seems to me that ded19fb would at least stop the warning as the warning occurs in `confint.thpr` but I'm not sure if that means the problem is totally solved. Even when I run the code explicitly with a `parm` argument of length 1, in my debugger it still has a length two `parm` object where the warning occurs (`parm` is `c("(Intercept)", "Days")`).

Try for example:

```
fm1P <- confint(fm1, method="profile", parm = "beta_")
```

This still throws the warning for me with the fixed effects coefficient names as `parm` argument being fed to the if statements in `confint.thpr`.

**Comment by bbolker** [comment] 2017-10-11 22:00
Hmm. I can't reproduce.  Have you tried with the most recent devel version?

**Comment by bbolker** [comment] 2017-10-13 19:36
Closing this; will reopen if someone else experiences it with most recent version.

**Comment by jacob-long** [comment] 2017-10-13 23:19
It is fixed with latest Github version. Thanks.

**Comment by kaz-yos** [comment] 2017-11-01 20:35
I experienced the same thing with 1.1-14 on macOS. In fact, this warning is seen in the CRAN Package Check Results.  I'll try out the latest dev version.

```
    ======== End of example output (where/before crash/hang up occured ?) ======== 
Flavor: r-devel-windows-ix86+x86_64

Version: 1.1-14 
Check: re-building of vignette outputs 
Result: NOTE 
    Error in re-building vignettes:
     ...
    Warning in test_latex_pkg("framed", system.file("misc", "framed.sty", package = "knitr")) :
     unable to find LaTeX package 'framed'; will use a copy from knitr
    Loading required package: Matrix
    Computing profile confidence intervals ...
    Warning in if (parm == "theta_") { :
     the condition has length > 1 and only the first element will be used
    Warning in if (parm == "beta_") { :
     the condition has length > 1 and only the first element will be used
```
https://cran.r-project.org/web/checks/check_results_lme4.html

**Comment by mmaechler** [comment] 2017-11-03 10:55
This is a warning in some cases --- where according to our users the resulting conf.intervals *are* wrong,
and an error in other cases, e.g.
```
example(lmer)
confint(fm2)
```
which gives
```
Computing profile confidence intervals ...
Error in if (parm == "theta_") { : the condition has length > 1
```

I was not happy with the code changes that lead to this,
 25b00a5 on Sep 12  (and I commented on that there)  and later
 ded19fbf on Sep 25
I'd really like to start from the code as it was before these changes and fix the bug / implement the feature that this was all about.  But I don't see any --> @bbolker  ??

**Comment by mmaechler** [comment] 2017-11-03 11:57
I am fixing the bug... (please let me do it).. there's a bit more than anticipated... and others duting calling, I will push hopefully in a few hours.

**Comment by bbolker** [comment] 2017-11-03 12:06
thanks @maechler .  Sorry for not responding to this sooner.

**Comment by mmaechler** [comment] 2017-11-04 11:17
Indeed, ce42eb4 does fix this issue

**Closed by mmaechler** 2017-11-04 11:17 UTC
Labels: bug

**Comment by wellerd2** [comment] 2017-11-21 14:48
Hi,

I hope all is well. I am using the confint function for a glmer model. And am getting the same message as the original poster (see below). I am new to GitHub and am not sure what else I need to include in this message to enable troubleshooting. I got the message when using trying to obtain confidence intervals for a bivariable model created using glmer. 

Best,

Dan

"Warning messages: 1: In if (parm == "theta_") { :
  the condition has length > 1 and only the first element will be used
2: In if (parm == "beta_") { :
  the condition has length > 1 and only the first element will be used"

**Comment by bbolker** [comment] 2017-11-21 14:58
This is fixed in the development version.  Can you try `devtools::install_github("lme4/lme4")` ? (@mmaechler: I'm finally making some progress with the reverse-dependency-checking infrastructure, so I think it will be reasonable to submit a new release to CRAN in the next week or so ...)

**Comment by wellerd2** [comment] 2017-11-21 15:07
Dear Dr. Bolker, 

Thanks so much. That worked.

Best,

Dan
